Feature/addsUnitTests
BlackWholeLabs/BlackNectar-iOS pull request #111
Opened 2017-01-18 22:45 UTC by cordhernandez

adds Unit Tests for all files
#103

2017-01-19 20:27 UTC, SirWellington requested changes
Love it! Just a few touches and it's good to go.

2017-01-19 20:27 UTC, SirWellington commented on BlackNectar/BlackNectar/StoresTableViewController.swift
> +    internal func loadStores(at coordinate: CLLocationCoordinate2D) {
`internal` is sort of implied, so you don't really need it.

2017-01-19 20:27 UTC, SirWellington commented on BlackNectar/BlackNectarTests/DistanceCalculationTests.swift
> +    func testGetDistance() {
Nice and clean!

2017-01-19 20:27 UTC, SirWellington commented on BlackNectar/BlackNectarTests/DistanceCalculationTests.swift
> +    func testMetersToMiles() {
Don't forget to test it with bad arguments. What happens when you pass in a negative number?

2017-01-19 20:27 UTC, SirWellington commented on BlackNectar/BlackNectarTests/DistanceCalculationTests.swift
> +        XCTAssertNotNil(DistanceCalculation.getDistance(userLocation: userslocation, storeLocation: restaurantsLocation))
The check should be more than "not nil". You should expected the distance to be, let's say 24 miles or whatever it actually is. This is what makes sure the distance formula works as expected.

2017-01-19 20:27 UTC, SirWellington commented on BlackNectar/BlackNectarTests/SearchStoresTest.swift
> +            if stores.isEmpty {
Think you meant `if !stores.isEmpty {`. The promise is fulfilled if the call returns stores.

2017-01-19 20:30 UTC, cordhernandez commented on BlackNectar/BlackNectar/StoresTableViewController.swift
> +    internal func loadStores(at coordinate: CLLocationCoordinate2D) {
got it done!

2017-01-19 20:30 UTC, cordhernandez commented on BlackNectar/BlackNectarTests/DistanceCalculationTests.swift
> +    func testGetDistance() {
thank you sir.

2017-01-23 01:33 UTC, cordhernandez commented on BlackNectar/BlackNectarTests/DistanceCalculationTests.swift
> +    func testMetersToMiles() {
+ will test with negative number
+ test passes with negative number

2017-01-23 01:35 UTC, cordhernandez commented on BlackNectar/BlackNectarTests/SearchStoresTest.swift
> +            if stores.isEmpty {
+ test fails with if !stores.isEmpty {
+ test passed with  if stores.isEmpty {

2017-01-23 01:36 UTC, cordhernandez commented on BlackNectar/BlackNectarTests/DistanceCalculationTests.swift
> +        XCTAssertNotNil(DistanceCalculation.getDistance(userLocation: userslocation, storeLocation: restaurantsLocation))
+ this is taking up more time than I thought 
+ this shouldn't take me this long but for some reason it is 
+ working on it

2017-01-23 01:55 UTC, SirWellington commented on BlackNectar/BlackNectarTests/SearchStoresTest.swift
> +            if stores.isEmpty {
Hmm, perhaps the test is trying to load stores somewhere in the world where there are none. Have you tried setting a breakpoint to see whether stores actually come back or not?

2017-01-23 01:56 UTC, SirWellington commented on BlackNectar/BlackNectarTests/DistanceCalculationTests.swift
> +    func testMetersToMiles() {
nice. The point was to add a separate test case specifically for those "Bad Arguments"
`testMetersToMilesWithBadArgs()`

2017-01-24 01:22 UTC, cordhernandez commented on BlackNectar/BlackNectarTests/SearchStoresTest.swift
> +            if stores.isEmpty {
Fixed this issue

2017-01-24 01:22 UTC, cordhernandez commented on BlackNectar/BlackNectarTests/DistanceCalculationTests.swift
> +    func testMetersToMiles() {
Oh ok
will add separate test case

2017-01-24 02:15 UTC, merged